name: 'LaSOT'
path: '${dataset.name}'
split_index_path: '${dataset.name}/.split_index.yaml'
history_len: 10
future_len: 1
additional_params:
  skip_occlusion: True
  skip_out_of_view: True
  image_load: False
  optical_flow: False
  image_shape: [224, 224]
  category_list:
    - 'airplane'