dataset:
  future_len: 1
  history_len: 10
  name: MOT20
  test_path: MOT20/test
  train_path: MOT20/train
  val_path: MOT20/val
eval:
  autoregressive: false
  autoregressive_keep_history: false
  batch_size: 32
  checkpoint: last.ckpt
  experiment: RNN-iter02-exp03-10h-1f-even-more-params
  inference_name: initial
  num_workers: 8
  split: val
model:
  params:
    hidden_dim: 64
    latent_dim: 64
    observable_dim: 4
  type: rnn
path:
  assets: /home/madzemovic/Desktop/personal-projects/NODETracker/assets
  master: /home/madzemovic/Desktop/personal-projects/NODETracker/outputs
resources:
  accelerator: cuda
  gpus: 1
  num_workers: 8
train:
  batch_size: 32
  checkpoint_cfg:
    metric_monitor: val/loss
    resume_from: null
  description: Using more parameters (previous version was underfitting)
  experiment: RNN-iter02-exp03-10h-1f-even-more-params
  logging_cfg:
    log_every_n_steps: 1
    path: logs
  max_epochs: 10
  resume_from_checkpoint: null
  train_params:
    learning_rate: 0.001
    sched_lr_gamma: 0.1
    sched_lr_step: 3
transform:
  name: standardized_first_difference
  params:
    mean: -0.0000865566333861711
    std: 0.0009227107879355021
visualize:
  fps: 10
  resolution:
    - 600
    - 400