name: 'filter-sort-tracker'
params:
  filter_name: node_kalman
  filter_params:
    accelerator: 'cuda:0'
    det_uncertainty_multiplier: 0.05
    buffer_size: 10
    buffer_min_size: 1
  remember_threshold: 30
  initialization_threshold: 3
  matcher_algorithm: byte_motion_assoc
  matcher_params:
    detection_threshold: 0.6
    match_threshold: 0.2
    motion_lambda: 5
    distance_name: 'l1'
    only_matched: false

  new_tracklet_detection_threshold: 0.7