name: 'filter-sort-tracker'
params:
  initialization_threshold: 3
  remember_threshold: 10

  matcher_algorithm: hungarian_iou
  matcher_params:
    match_threshold: 0.3

  filter_name: 'node_kalman'
  filter_params:
    accelerator: 'cuda:0'
    buffer_size: 10
    buffer_min_size: 1
    det_uncertainty_multiplier: 0.05