defaults:
  - filter: akf
  - selection: default.yaml
  - object_detection: gt.yaml


lookup_path: '/home/robotmurlock/Desktop/datasets/LaSOT-YOLO/YOLO-LaSOT/lookup.json'
# lookup_path: '/media/home/nodetracker-outputs/lookup.json'
# lookup_path: '/media/home/LaSOT-YOLO-baseline-lower-lr/lookup.json'

eval:
  n_steps: 1

jitter:
  detection_noise_sigma: 0.00
  detection_skip_proba: 0.00

visualization:
  enable: False