defaults:
  # - filter: rnn_kalman.yaml
  - filter: buffered_node_model.yaml
  - selection: good_od.yaml
  - object_detection: yolo.yaml


lookup_path: '/home/robotmurlock/Desktop/datasets/LaSOT-YOLO/YOLO-LaSOT/lookup.json'
# lookup_path: '/media/home/nodetracker-outputs/lookup.json'
# lookup_path: '/media/home/LaSOT-YOLO-baseline-lower-lr/lookup.json'

eval:
  n_steps: 1
  # disable_eval_after_n_fns: 1
  disable_eval_after_n_fns: 30

jitter:
  detection_noise_sigma: 0.00
  detection_skip_proba: 0.00

es:
  # min_iou_match: 0.1
  min_iou_match: 0.0

visualization:
  enable: False