defaults:
  - filter: node_model.yaml

lookup_path: '/media/home/nodetracker-outputs/lookup.json'

object_detection:
  type: 'ground_truth'
  params: {}

eval:
  n_steps: 1

jitter:
  detection_noise_sigma: 0.00
  detection_skip_proba: 0.00

visualization:
  enable: False