filter:
  type: 'node'
  params:
    accelerator: 'cuda:0'
    det_std: [0.01, 0.01, 0.01, 0.01]

    buffer_size: 10
    buffer_min_size: 1
#  type: 'akf'
#  params:
#    use_optimal_motion_mat: True

lookup_path: '/media/home/nodetracker-outputs/lookup.json'

object_detection:
  type: 'ground_truth'
  params: {}

visualization:
  enable: False