type: node_filter
params:
  observable_dim: 12
  output_dim: 4
  latent_dim: 128

  homogeneous: False
  bounded_variance: False
  rnn_update_layer: True
  augmentation_remove_points_enable: True
  augmentation_remove_random_points_proba: 0.05
  augmentation_remove_sequence_proba: 0.05

  solver_name: 'rk4'
  solver_params:
    max_step_size: 0.25
