type: node_filter
params:
  observable_dim: 4
  output_dim: 4
  latent_dim: 128

  homogeneous: True
  bounded_variance: True
  rnn_update_layer: True

  solver_name: 'rk4'
  solver_params:
    max_step_size: 0.25
