name: 'LaSOT'
path: '${dataset.name}'
split_index_path: '${dataset.name}/.split_index.yaml'
history_len: 10
future_len: 1
additional_params:
  skip_occlusion: True
  skip_out_of_view: True
#  category_list:
#    - 'airplane'