defaults:
  # - object_detection: yolox.yaml
  - object_detection: sportsmot_yolox.yaml
  - algorithm: rnnode_sort.yaml

lookup_path: '/media/home/DanceTrack/.lookup.json'
output_path: 'tracker_inference'