defaults:
  - resources: cuda.yaml
  - dataset: dancetrack/default.yaml
  - transform: dancetrack/standardized_first_difference.yaml
  - model: attn_cnp.yaml
  - train: attn_cnp.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: lasot/obs_only.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - tracker: rnnode_sort.yaml
  - _self_
