defaults:
  - resources: cuda.yaml
  - dataset: mot.yaml
  - transform: standardized_relative_to_last_obs_with_noise.yaml
  - model: mlpode.yaml
  - train: mlpode.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: detector_noise.yaml
  - _self_
