defaults:
  - resources: cuda.yaml
  - dataset: lasot.yaml
  - transform: standardized_first_difference.yaml
  - model: node_filter.yaml
  - train: node_filter.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: lasot/node_filter_default.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - _self_
