defaults:
  - resources: cuda.yaml
  # - dataset: lasot.yaml
  # - dataset: mot.yaml
  - dataset: dancetrack/default.yaml
  - transform: lasot/jack_of_all_trades.yaml
  - model: node_filter.yaml
  - train: node_filter.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: lasot/node_filter_default.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - tracker: default.yaml
  - _self_
