defaults:
  - resources: cuda.yaml
  - dataset: sportsmot/h30f60.yaml
  - transform: sportsmot/jack_of_all_trades_scaled.yaml
#  - dataset: dancetrack/default.yaml
#  - transform: dancetrack/jack_of_all_trades_v2.yaml
  - model: node_filter.yaml
  - train: node_filter.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: node_filter_less_noise.yaml
  - path: default.yaml
  - end_to_end: default.yaml
  - tracker: node_sort.yaml
  # - tracker: sort_kf.yaml
  - _self_
