dataset:
  future_len: 5
  history_len: 10
  name: MOT20
  test_path: MOT20/test
  train_path: MOT20/train
  val_path: MOT20/val
eval:
  autoregressive: false
  autoregressive_keep_history: false
  batch_size: 32
  checkpoint: last.ckpt
  experiment: ODERNN-iter02-exp10-10h-weaker-wd
  inference_name: initial
  num_workers: 8
  split: val
model:
  params:
    hidden_dim: 32
    observable_dim: 4
    solver_name: rk4
    solver_params:
      max_step_size: 0.25
  type: odernn
path:
  assets: /home/robotmurlock/Desktop/projects/NODETracker/assets
  master: /home/robotmurlock/Desktop/projects/NODETracker/outputs
resources:
  accelerator: cuda
  gpus: 1
  num_workers: 8
train:
  batch_size: 32
  checkpoint_cfg:
    metric_monitor: val/loss
    resume_from: null
  description: ODE-RNN-L-AdamW-fixed-standardization
  experiment: ODE-RNN-L with AdamW and fixed standardization
  logging_cfg:
    log_every_n_steps: 1
    path: logs
  max_epochs: 10
  train_params:
    learning_rate: 0.001
    sched_lr_gamma: 0.1
    sched_lr_step: 3
    weight_decay: 0.005
transform:
  name: standardized_first_difference
  params:
    mean:
    - 0.00017640840087551624
    - -0.0005187939386814833
    - 1.206293745781295e-05
    - 1.3928008684160886e-06
    std:
    - 0.001025039586238563
    - 0.0012134865391999483
    - 0.0005178151186555624
    - 0.0007754131802357733
visualize:
  fps: 10
  resolution:
    - 600
    - 400
