defaults:
  - resources: cuda.yaml
  - dataset: mot.yaml
  - transform: standardized_first_difference_v2.yaml
  - model: odernnvae.yaml
  - train: odernnvae.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: default.yaml
  - _self_