defaults:
  - resources: cuda.yaml
  - dataset: mot.yaml
  - transform: standardized_first_difference.yaml
  - model: odernnvae.yaml
  - train: odernnvae.yaml
  - eval: odernnvae.yaml
  - visualize: default.yaml
  - _self_