defaults:
  - resources: cuda.yaml
  - dataset: mot.yaml
  - transform: standardized_first_difference_with_noise.yaml
  - model: odernn.yaml
  - train: odernn.yaml
  - eval: odernn.yaml
  - visualize: default.yaml
  - augmentations: detector_noise.yaml
  - _self_
