defaults:
  - resources: cuda.yaml
  - dataset: mot.yaml
  - transform: standardized_first_difference.yaml
  - model: odevae.yaml
  - train: odevae.yaml
  - eval: odevae.yaml
  - visualize: default.yaml
  - augmentations: default.yaml
  - _self_
