defaults:
  - resources: cuda.yaml
  - dataset: mot.yaml
  - transform: standardized_first_difference.yaml
  - model: rnn.yaml
  - train: rnn.yaml
  - eval: rnn.yaml
  - visualize: default.yaml
  - _self_