defaults:
  - resources: cuda.yaml
  - dataset: dancetrack/default.yaml
  - transform: dancetrack/standardized_relative_to_last_obs_with_pads.yaml
  - model: rnn_cnp.yaml
  - train: rnn_cnp.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: less_noise_pad.yaml
  - path: default.yaml
  - end_to_end: default.yaml
  - tracker: rnnode_sort.yaml
  - _self_
