defaults:
  - resources: cuda.yaml
  - dataset: lasot/default.yaml
  - transform: lasot/jack_of_all_trades.yaml
  - model: rnn_filter.yaml
  - train: rnn_filter.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: node_filter_default.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - tracker: rnnode_sort.yaml
  - _self_