defaults:
  - resources: cuda.yaml
  - dataset: lasot.yaml
  - transform: lasot/standardized_relative_to_last_obs.yaml
  - model: rnn_cnp_filter.yaml
  - train: rnn_cnp_filter.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: lasot/node_filter_default.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - _self_
