defaults:
  - resources: cuda.yaml
  - dataset: mot20/h30f60.yaml
  - transform: mot20/standardized_first_difference_scaled.yaml
  - model: rnn_cnp.yaml
  - train: rnn_cnp.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: less_noise.yaml
  - path: default.yaml
  - end_to_end: default.yaml
  - tracker: rnnode_sort.yaml
  - _self_
