defaults:
  - resources: cuda.yaml
  - dataset: mot17/default.yaml
  - transform: mot17/standardized_first_difference.yaml
  - model: rnn_cnp.yaml
  - train: rnn_cnp.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: camera_movement.yaml
  - path: default.yaml
  - end_to_end: default.yaml
  - tracker: rnnode_sort.yaml
  - _self_
