defaults:
  - resources: cuda.yaml
  # - dataset: lasot.yaml
  - dataset: dancetrack/default.yaml
  - transform: dancetrack/standardized_relative_to_last_obs.yaml
  - model: rnn_cnp.yaml
  - train: rnn_cnp.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: lasot/obs_only.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - _self_
