defaults:
  - resources: cuda.yaml
  - dataset: lasot.yaml
  - transform: lasot/jack_of_all_trades.yaml
  - model: rnnode.yaml
  - train: rnnode.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: lasot/default.yaml
  - path: lasot.yaml
  - end_to_end: node.yaml
  - _self_
