defaults:
  - resources: cuda.yaml
  - dataset: dancetrack/default.yaml
  - transform: dancetrack/jack_of_all_trades.yaml
  - model: rnnode.yaml
  - train: rnnode.yaml
  - eval: default.yaml
  - visualize: default.yaml
  - augmentations: lasot/obs_only.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - tracker: rnnode_sort.yaml
  - _self_
