defaults:
  - resources: cuda.yaml
  - dataset: mot.yaml
  - transform: standardized_relative_to_last_obs.yaml
  - model: rnnode.yaml
  - train: rnnode.yaml
  - eval: rnnode.yaml
  - visualize: default.yaml
  - augmentations: default.yaml
  - _self_
