augmentations:
  after_batch_collate_config:
    _target_: nodetracker.datasets.augmentations.trajectory.IdentityAugmentation
  after_transform_config:
    _target_: nodetracker.datasets.augmentations.trajectory.IdentityAugmentation
  before_transform_config:
    _target_: nodetracker.datasets.augmentations.trajectory.IdentityAugmentation
dataset:
  additional_params:
    skip_occlusion: true
    skip_out_of_view: true
  future_len: 5
  history_len: 10
  name: LaSOT
  path: LaSOT
  split_index_path: LaSOT/.split_index.yaml
eval:
  autoregressive: false
  autoregressive_keep_history: false
  batch_size: 1024
  checkpoint: last.ckpt
  dataset_future_len: null
  experiment: RNNODE-lasot-exp10-128dim-no-occ-no-oov-fixed-data-sampling
  inference_name: initial
  split: val
model:
  params:
    hidden_dim: 128
    model_gaussian: true
    observable_dim: 4
    solver_name: rk4
    solver_params:
      max_step_size: 0.25
  type: rnnode
path:
  assets: /home/robotmurlock/Desktop/datasets
  master: /home/robotmurlock/Desktop/LaSOT-output
resources:
  accelerator: cuda
  devices: 1
  num_workers: 8
train:
  batch_size: 256
  checkpoint_cfg:
    metric_monitor: val-epoch/loss
    resume_from: null
  description: RNNODE - 128dim
  experiment: RNNODE-lasot-exp10-128dim-no-occ-no-oov-fixed-data-sampling
  gradient_clip_algorithm: value
  gradient_clip_val: 100
  inverse_transform_before_loss: true
  logging_cfg:
    log_every_n_steps: 1
    path: logs
  max_epochs: 30
  train_params:
    learning_rate: 0.001
    loss_name: gaussian_nllloss
    loss_params: {}
    optim_name: adamw
    sched_lr_gamma: 0.1
    sched_lr_step: 8
    weight_decay: 0.0001
transform:
  name: standardized_relative_to_last_obs
  params:
    mean:
    - -3.220816324756015e-06
    - 2.2988066120888107e-05
    - 1.509633057139581e-05
    - 6.674266478512436e-05
    std:
    - 0.027728525921702385
    - 0.03423177823424339
    - 0.018333032727241516
    - 0.024016927927732468
visualize:
  fps: 10
  resolution:
  - 600
  - 400
end_to_end:
  filter:
    type: 'akf'
    params:
      use_optimal_motion_mat: True
  selection:
    scene: '^airplane[-](.*?)$'
  visualization:
    enable: True
    prior: True
    posterior: False

  object_detection:
    type: 'yolo'
    params:
      model_path: '/home/robotmurlock/Desktop/projects/NODETracker/runs/detect/LaSOT-baseline-40epoch-airplane/weights/last.pt'
      accelerator: 'cuda:0'
