defaults:
  - resources: cuda.yaml
  - dataset: mot17/h20f1.yaml
  - transform: mot17/jack_of_all_trades_scaled.yaml
  - model: single_step_rnn.yaml
  - train: single_step_rnn.yaml
  - eval: autoregressive.yaml
  - visualize: default.yaml
  - augmentations: less_noise.yaml
  - path: default.yaml
  - end_to_end: default.yaml
  - tracker: rnn_sort.yaml
  - _self_
