defaults:
  - resources: cuda.yaml
  - dataset: lasot10_1.yaml
  # - dataset: mot.yaml
  - transform: lasot/standardized_first_difference.yaml
  - model: single_step_rnn.yaml
  - train: single_step_rnn.yaml
  - eval: autoregressive.yaml
  - visualize: default.yaml
  - augmentations: lasot/no_augs.yaml
  - path: lasot.yaml
  - end_to_end: default.yaml
  - _self_
