defaults:
  - resources: cuda.yaml
#  - dataset: sportsmot/h30f1.yaml
#  - transform: sportsmot/jack_of_all_trades_scaled.yaml
  - dataset: dancetrack/dancetrack10_1.yaml
  - transform: dancetrack/jack_of_all_trades_v2.yaml
  - model: single_step_rnn.yaml
  - train: single_step_rnn.yaml
  - eval: autoregressive.yaml
  - visualize: default.yaml
  - augmentations: less_noise.yaml
  - path: default.yaml
  - end_to_end: default.yaml
  - tracker: rnn_sort.yaml
  - _self_
