defaults:
  - resources: cuda.yaml
  - dataset: lasot10_1.yaml
  - transform: identity.yaml
  - model: takf.yaml
  - train: takf.yaml
  - eval: takf.yaml
  - visualize: default.yaml
  - augmentations: default.yaml
  - _self_