# experiment: 'BaselineAttnCNP-SportsMOT-exp02-256-h30f60-RelUnobs'
experiment: 'BaselineAttnCNP-dancetrack-exp04-256dim-wd'
description: 'Baseline AttnCNP, x160 (LaSOT optimal)'
batch_size: 256
max_epochs: 15

inverse_transform_before_loss: True
gradient_clip_val: 100
gradient_clip_algorithm: value

train_params:
  optim_name: adam
  learning_rate: 1e-4
  n_warmup_epochs: 3
  sched_lr_gamma: 0.1
  sched_lr_step: 6
  weight_decay: 1e-4

  loss_name: 'gaussian_nllloss'
  loss_params: {}

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val-epoch/loss'
  resume_from: null