experiment: 'KalmanFilter-exp01'
description: 'Kalman Filter model requires no training.'
batch_size: 1
max_epochs: 0
learning_rate: 0

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null