experiment: 'NODEFilterModel-lasot-exp27-128dim-warmup-slower-training'
description: 'NODEFilter - 128dim - joat - augs - RNN update - special augmentation in the trainer - 5 steps - wd'
batch_size: 256
learning_rate: 1e-3
max_epochs: 30

inverse_transform_before_loss: True
gradient_clip_val: 100
gradient_clip_algorithm: value

train_params:
  optim_name: adam
  learning_rate: 1e-4
  n_warmup_epochs: 3
  sched_lr_gamma: 0.1
  sched_lr_step: 6
  weight_decay: 0.0000

  loss_name: 'gaussian_nllloss'
  loss_params: {}

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val-epoch/loss'
  resume_from: null
