experiment: 'ODERNNVAE-exp03-scheduler'
description: 'ODERNNVAE like exp02 but with lr scheduler.'
batch_size: 32
learning_rate: 1e-3
max_epochs: 10

train_params:
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 3

resume_from_checkpoint: null