experiment: 'ODERNN-iter03-exp07-um-AdamW-detector-noise-updated-transform-stats'
description: 'ODERNN with uncertainty modeling and AdamW optimizer with added detector noise augmentations (p=0.5) - updated stats'
batch_size: 32
learning_rate: 1e-3
max_epochs: 15

train_params:
  optim_name: adamw
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 4
  weight_decay: 0.01

resume_from_checkpoint: null

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null
