experiment: 'RNN-iter02-exp03-10h-1f-even-more-params'
description: 'Using more parameters (previous version was underfitting)'
batch_size: 32
learning_rate: 1e-3
max_epochs: 10

train_params:
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 3

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null
