# experiment: 'BaselineRNNCNP-SportsMOT-exp05-384-h30f60-RelUnobs'
# experiment: 'BaselineRNNCNP-dancetrack-exp02-256-R4'
experiment: 'BaselineRNNCNP-SportsMOT-exp03-256-h30f60-RelUnobs'
description: 'Baseline RNN-CNP, warmup'
batch_size: 256
learning_rate: 1e-3
max_epochs: 20

inverse_transform_before_loss: True
gradient_clip_val: 100
gradient_clip_algorithm: value

train_params:
  optim_name: adam
  learning_rate: 1e-4
  n_warmup_epochs: 3
  sched_lr_gamma: 0.1
  sched_lr_step: 3
  weight_decay: 1e-4

  loss_name: 'gaussian_nllloss'
  loss_params: {}

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val-epoch/loss'
  resume_from: null