experiment: 'RNNODE-lasot-exp04-dog-cat-turtle-robot-airplane-64dim-MOT20-checkpoint'
description: 'RNNODE - five categories - 64dim. Checkpoint=outputs/MOT20/RNNODE-iter03-exp03-double-params/checkpoints/last.ckpt'
batch_size: 32
learning_rate: 1e-3
max_epochs: 25

train_params:
  optim_name: adamw
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 4
  weight_decay: 0.00

resume_from_checkpoint: null

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: '/home/madzemovic/NODETracker-tmp/outputs/MOT20/RNNODE-iter03-exp03-double-params/checkpoints/last.ckpt'
