# experiment: 'RNNODE-SportsMOT-exp01-256-h30f60-RelObs'
# experiment: 'RNNODE-dancetrack-exp02-256dim'
experiment: 'RNNODE-SportsMOT-exp01-256-h30f60-RelObs'
description: 'RNNODE MOT17 baseline (optimal LaSOT), x256'
batch_size: 256
learning_rate: 1e-3
max_epochs: 12

inverse_transform_before_loss: True
gradient_clip_val: 100
gradient_clip_algorithm: value

train_params:
  optim_name: adamw
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 4
  weight_decay: 0.01

  loss_name: 'gaussian_nllloss'
  loss_params: {}

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val-epoch/loss'
  resume_from: null
