experiment: 'RNNODE-lasot-exp04-128dim-no-occ-no-oov-long-train-hybrid_gaussian_nllloss_giou'
description: 'RNNODE - full dataset - 64dim. No out of view and occlusion in training. Using hybrid_gaussian_nllloss_giou.'
batch_size: 64
learning_rate: 1e-3
max_epochs: 20

train_params:
  optim_name: adamw
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 5
  weight_decay: 0.0001

  loss_name: 'hybrid_gaussian_nllloss_giou'
  loss_params:
    w_nllloss: 5
    w_giou: 1

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null
