experiment: 'RNNODE-lasot-exp02-dog-cat-turtle-robot-airplane-full-train'
description: 'RNNODE - five categories'
batch_size: 32
learning_rate: 1e-3
max_epochs: 15

train_params:
  optim_name: adamw
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 4
  weight_decay: 0.00

resume_from_checkpoint: null

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null
