experiment: 'RNNODE-lasot-exp06-dog-cat-turtle-robot-airplane-64dim-no-oov-no-occ-long-train'
description: 'RNNODE - five categories - 64dim. No occlusions and no out of view in training. Long train, bigger batch size.'
batch_size: 64
learning_rate: 1e-3
max_epochs: 20

train_params:
  optim_name: adamw
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 5
  weight_decay: 0.00

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null
