experiment: 'RNNODE-lasot-exp02-64dim-no-occ-no-oov-long-train'
description: 'RNNODE - full dataset - 64dim. No out of view and occlusion in training. Long train, bigger batch size, weight decay.'
batch_size: 64
learning_rate: 1e-3
max_epochs: 20

train_params:
  optim_name: adamw
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 5
  weight_decay: 0.0001

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null
