experiment: 'RNNODE-lasot-exp04-128dim-no-occ-no-oov-long-train-inverse-func'
description: 'RNNODE - full dataset - 128dim. No out of view and occlusion in training. Using inverse transform func before.'
batch_size: 64
learning_rate: 1e-2
max_epochs: 20

inverse_transform_before_loss: True

train_params:
  optim_name: adamw
  learning_rate: 1e-2
  sched_lr_gamma: 0.1
  sched_lr_step: 5
  weight_decay: 0.0001

  loss_name: 'gaussian_nllloss'

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: null
