experiment: 'TAKF-LaSOT-iter01-exp03-train-uncertainty-with-likelihood'
description: 'Training uncertainty parameters (pretrained motion model) - with likelihood'
batch_size: 128
learning_rate: 1e-3
max_epochs: 30

train_params:
  learning_rate: 1e-3
  sched_lr_gamma: 0.1
  sched_lr_step: 4

logging_cfg:
  path: 'logs'
  log_every_n_steps: 1

checkpoint_cfg:
  metric_monitor: 'val/loss'
  resume_from: '/home/madzemovic/NODETracker-tmp/outputs/LaSOT/TAKF-LaSOT-iter01-exp01-motion-first-principles-triu-motion-only-frozen-diag-longer-train/checkpoints/last.ckpt'
